# Generated by Django 4.2.20 on 2025-06-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField()),
                ('order_num', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('cert_num', models.IntegerField()),
                ('mpp', models.IntegerField()),
                ('bank', models.BooleanField()),
                ('ese', models.DateField()),
                ('needs_course', models.BooleanField()),
                ('has_course', models.DateField()),
                ('reading_comp', models.DateField()),
                ('needs_fels', models.BooleanField()),
                ('has_fels', models.DateField()),
                ('pending', models.CharField(max_length=50)),
                ('returned', models.DateField()),
                ('done', models.DateField()),
                ('alert', models.BooleanField()),
                ('cert_notes', models.TextField()),
                ('purchase_notes', models.TextField()),
            ],
        ),
    ]
