# Generated by Django 5.2.4 on 2025-07-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='cert_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='done',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pending',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payments',
            name='reading_comp',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='returned',
            field=models.DateField(blank=True),
        ),
    ]
