# Generated by Django 5.2.4 on 2025-07-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payments_cert_num_alter_payments_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='done',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='has_fels',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pending',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='reading_comp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
